languageCode = "en-us"
title = "Lekkere recepten"
baseurl = "https://ronsmits.org/recepten"
theme     = "bootie-docs"

[params]
  description    = "Recepten die ik netjes ingetypt heb."
  withSitePosts  = true
  searchDomain   = "ronsmits.org"
  #noCategoryLink = true
  #repositoryUrl  = "http://your-repository-url"
  highlightStyle = "github"

